services:
  analysis-env:
    image: xcyss/dockerfile-practice
    ports:
      - "8787:8787"
    volumes:
      - .:/home/rstudio/work
    environment:
      PASSWORD: "password"
      DISABLE_AUTH: true
